version: "3"

services:

  myrabbit:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=root      
      - RABBITMQ_DEFAULT_PASS=w9jTwtNi1wm4Q3VPUfBecPWd
    # ports: #暂时使用
    #   - "15672:15672"
    expose:
        - "5672"   
        - "15672"     #控制版面nginx代理访问
    restart: always   #always表容器运行发生错误时一直重启

  myredis:
    image: redis:latest
    command: redis-server
    volumes:
      - ./compose/redis:/data
    ports:
      - "6379:6379"
    restart: always 

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=youngtrip                     # 数据库名称
      - MYSQL_ROOT_PASSWORD=w9jTwtNi1wm4Q3VPUfBecPWd # 数据库密码
    volumes:
      - ./compose/mysql/data:/var/lib/mysql               # 挂载数据库数据
      - ./compose/mysql/conf/my.cnf:/etc/mysql/my.cnf     # 挂载配置文件
      - ./compose/mysql/init:/docker-entrypoint-initdb.d/ # 挂载数据初始化sql脚本
    ports:
      - "3306:3306"
    restart: always

  web:
    build: ./compose/django
    ports:
      - "8000:8000"   
      # - "5555:5555" #暂时使用
    expose:
      - "5672"   
      - "5555"   
      - "8000"
    volumes: 
      - ./src:/app   # - /tmp/logs:/tmp
    command: bash ./start.sh
    links:
      - myrabbit
      - db
      - myredis
    depends_on:     #先后启动顺序，DJango依赖于db和redis
      - myrabbit
      - db
      - myredis
    restart: always

  nginx:
    build: ./compose/nginx
    ports:
      - "80:80"
      - "443:443"
      - "15672:15672"
      - "5555:5555"
    expose:
      - "8000"
      - "15672"
      - "5555"
    volumes:
      - ./src/static:/usr/share/nginx/html/static     # 挂载静态文件
      - ./src/media:/usr/share/nginx/html/media       # 挂载上传文件
      - ./compose/nginx/ssl:/usr/share/nginx/ssl   # 挂载ssl证书目录
    links:
      - myrabbit
      - web
    depends_on:
      - myrabbit
      - web
    restart: always